const APICULTURE_COURSE = {
  title: 'Formation pratique en apiculture',
  subtitle: 'Apprenez à installer, suivre et valoriser un rucher avec des gestes simples, sécurisés et adaptés au terrain.',
  modules: [
    {
      id: 'm1',
      title: 'Bienvenue et orientation',
      description: 'Comprendre le parcours, les objectifs et la méthode de travail.',
      lessons: [
        {
          id: 'm1-l1',
          title: 'Bienvenue dans la formation',
          duration: '8 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-1-bienvenue.pdf',
          summary: 'Présentation du parcours, des résultats attendus et de la manière d’utiliser les vidéos, PDF et exercices de suivi.',
        },
        {
          id: 'm1-l2',
          title: 'Organisation du carnet de suivi',
          duration: '12 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-1-carnet-suivi.pdf',
          summary: 'Mise en place d’un carnet simple pour noter les visites, les observations, les interventions et les prochaines actions.',
        },
      ],
    },
    {
      id: 'm2',
      title: 'Comprendre la colonie d’abeilles',
      description: 'Identifier les rôles des abeilles et les besoins biologiques de la colonie.',
      lessons: [
        {
          id: 'm2-l1',
          title: 'La reine, les ouvrières et les faux-bourdons',
          duration: '15 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-2-roles-colonie.pdf',
          summary: 'Repères essentiels pour reconnaître les castes de la colonie et comprendre leurs rôles dans la ruche.',
        },
        {
          id: 'm2-l2',
          title: 'Cycle de vie et dynamique saisonnière',
          duration: '18 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-2-cycle-vie.pdf',
          summary: 'Lecture du développement de la colonie au fil des saisons afin d’anticiper les besoins en nourriture, espace et surveillance.',
        },
        {
          id: 'm2-l3',
          title: 'Signes d’une colonie saine',
          duration: '14 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-2-colonie-saine.pdf',
          summary: 'Liste des indicateurs visuels et comportementaux à observer pour vérifier la vitalité de la colonie.',
        },
      ],
    },
    {
      id: 'm3',
      title: 'Matériel apicole essentiel',
      description: 'Choisir les équipements de base pour travailler proprement et en sécurité.',
      lessons: [
        {
          id: 'm3-l1',
          title: 'Ruche, cadres et petits outils',
          duration: '16 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-3-materiel-ruche.pdf',
          summary: 'Présentation du matériel indispensable pour débuter, entretenir la ruche et manipuler les cadres correctement.',
        },
        {
          id: 'm3-l2',
          title: 'Protection, enfumoir et hygiène',
          duration: '13 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-3-protection-hygiene.pdf',
          summary: 'Bonnes pratiques pour se protéger, utiliser l’enfumoir avec mesure et garder un environnement de travail propre.',
        },
      ],
    },
    {
      id: 'm4',
      title: 'Choisir et installer un rucher',
      description: 'Évaluer un emplacement et installer les ruches dans de bonnes conditions.',
      lessons: [
        {
          id: 'm4-l1',
          title: 'Critères de choix du terrain',
          duration: '17 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-4-choix-terrain.pdf',
          summary: 'Méthode pour évaluer l’accessibilité, l’eau, les ressources florales, l’ombre, le vent et le voisinage.',
        },
        {
          id: 'm4-l2',
          title: 'Installation et orientation des ruches',
          duration: '14 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-4-installation-rucher.pdf',
          summary: 'Étapes pratiques pour poser, orienter et espacer les ruches afin de faciliter le travail et limiter les risques.',
        },
        {
          id: 'm4-l3',
          title: 'Gestion des risques autour du rucher',
          duration: '11 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-4-risques-rucher.pdf',
          summary: 'Mesures simples pour réduire les nuisances, protéger les visiteurs et anticiper les incidents près du rucher.',
        },
      ],
    },
    {
      id: 'm5',
      title: 'Visite et suivi des colonies',
      description: 'Observer les colonies, noter les informations clés et planifier les actions.',
      lessons: [
        {
          id: 'm5-l1',
          title: 'Préparer une visite de ruche',
          duration: '10 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-5-preparer-visite.pdf',
          summary: 'Checklist de préparation pour intervenir au bon moment, avec le bon matériel et un objectif clair.',
        },
        {
          id: 'm5-l2',
          title: 'Lecture des cadres et prise de notes',
          duration: '19 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-5-lecture-cadres.pdf',
          summary: 'Observation du couvain, des réserves, de l’activité et des anomalies, puis rédaction de notes utiles.',
        },
        {
          id: 'm5-l3',
          title: 'Actions correctives simples',
          duration: '16 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-5-actions-correctives.pdf',
          summary: 'Exemples d’actions de base lorsque la colonie manque d’espace, de nourriture ou demande une surveillance rapprochée.',
        },
      ],
    },
    {
      id: 'm6',
      title: 'Récolte, qualité et conservation du miel',
      description: 'Récolter au bon moment et conserver un miel propre et commercialisable.',
      lessons: [
        {
          id: 'm6-l1',
          title: 'Reconnaître le bon moment de récolte',
          duration: '12 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-6-moment-recolte.pdf',
          summary: 'Critères pour décider si le miel est prêt, en tenant compte des cadres operculés et des conditions du rucher.',
        },
        {
          id: 'm6-l2',
          title: 'Extraction, filtration et décantation',
          duration: '20 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-6-extraction-miel.pdf',
          summary: 'Processus propre d’extraction du miel, de filtration et de repos avant conditionnement.',
        },
        {
          id: 'm6-l3',
          title: 'Conditionnement et conservation',
          duration: '13 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-6-conservation-miel.pdf',
          summary: 'Conseils pour mettre en pot, stocker et protéger la qualité du miel jusqu’à la vente ou la consommation.',
        },
      ],
    },
    {
      id: 'm7',
      title: 'Commercialisation simple',
      description: 'Préparer une offre claire et vendre le miel de manière professionnelle.',
      lessons: [
        {
          id: 'm7-l1',
          title: 'Calculer ses coûts et fixer un prix',
          duration: '15 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-7-prix-miel.pdf',
          summary: 'Méthode simple pour additionner les coûts, intégrer la marge et définir un prix cohérent.',
        },
        {
          id: 'm7-l2',
          title: 'Présentation, étiquette et confiance client',
          duration: '14 min',
          videoEmbedUrl: 'https://www.youtube.com/embed/VIDEO_ID_A_REMPLACER',
          pdfUrl: 'assets/documents/module-7-presentation-produit.pdf',
          summary: 'Amélioration de la présentation du produit, de l’étiquette et des messages qui rassurent les clients.',
        },
      ],
    },
  ],
};
